repos:
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
          - mdformat-config
          - mdformat-toc
  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: '.*\.(yaml|yml)'
      - id: trailing-whitespace
      - id: requirements-txt-fixer
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
  - repo: https://github.com/DetachHead/basedpyright-pre-commit-mirror
    rev: 1.29.1
    hooks:
      - id: basedpyright
        language: system
  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.6
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          - -rn # Only display messages
          - -sn # Don't display the score
  - repo: https://github.com/hadolint/hadolint.git
    rev: v2.13.1-beta
    hooks:
      - id: hadolint
