repos:
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.22
  hooks:
    - id: mdformat
      additional_dependencies:
        - mdformat-gfm
        - mdformat-black
        - mdformat-config
        - mdformat-toc
